version: '3.8'

services:
  grpc-app:
    environment:
      - SPRING_R2DBC_URL=r2dbc:postgresql://book:5432/bookdb
      - SPRING_FLYWAY_URL=jdbc:postgresql://book:5432/bookdb
      - FLYWAY_USER=root
      - FLYWAY_PASSWORD=root
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grpc-app
    expose:
      - "9090"
    ports:
      - "9090:9090"
      - "8080:8080"
  book:
    image: postgres:alpine
    container_name: book
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=bookdb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  test-db:
    image: postgres:alpine
    container_name: test-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test