spring:
  flyway:
    enabled: true
    create-schemas: true
    locations: classpath:db/migration
    url: jdbc:postgresql://localhost:5432/bookdb
    user: root
    password: root
  data:
    r2dbc:
      repositories:
        enabled: true
  application:
    name: grpc-task
  r2dbc:
    name: bookdb
    password: root
    username: root
    url: r2dbc:postgresql://localhost:5432/bookdb
    pool:
      max-size: 30
      initial-size: 20
springdoc:
  swagger-ui:
    path: /swagger-ui.html
grpc:
  server:
    port: 9090
    reflection-service-enabled: true
server:
  port: 8080